### PR TITLE
Sphinx update requirement and include references

### PR DESCRIPTION
**Pull request by mosesyhc**
I made a draft section under use cases for a bibliography of references that use surmise.  Feel free to edit.

### CODE REVIEW

**Comment by mosesyhc** [comment]
Requires manual `make html` though.
Make sure `sphinx>=7.2` and `sphinx-rtd-theme` is installed.

**Review by wildsm — APPROVED** [review]
Thanks, looks fine to me

**Comment by mosesyhc** [comment]
@ozgesurer: I want to make sure nothing obvious is missing in the bibliography.  That'd be all we need to review.

**Comment by ozgesurer** [comment]
Sure @mosesyhc. I will take a look at it tonight, if not, tomorrow. Sorry, I needed to take care of some personal stuff this weekend, and I'm running behind.

**Comment by mosesyhc** [comment]
@ozgesurer Tomorrow or Tuesday is fine. Today is Sunday 🙂

**Comment by ozgesurer** [comment]
@mosesyhc I am not able to find the bibliography of references that use surmise under use cases. Do you think that you push the associated changes to this PR?

**Comment by mosesyhc** [comment]
@ozgesurer: Check this .bib file (docs/surmise.bib) for the references.  The documentation html is not updated unless `make` is run manually, or readthedocs runs `make`

**Comment by ozgesurer** [comment]
I got it. Everything looks great. Merging...

**Pull request merged**
