### PR TITLE
SDKv0.2

### PR DESCRIPTION
**Pull request by ozgesurer**

### CODE REVIEW

**Comment by ozgesurer** [comment]
Please approve this for SDK update

**Comment by wildsm** [comment]
@ozgesurer - can you please reformat the Website: / Contact / Icon / Description (see frescoxbandsk)?

**Comment by ozgesurer** [comment]
@wildsm Changes are done.

**Comment by wildsm** [comment]
The
[M2 details](https://github.com/surmising/surmise/pull/38#m2-details)
should be moved from R14 to M2

**Review by wildsm — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
