### PR TITLE
ROSE integration currently handled by surmise

### PR DESCRIPTION
**Pull request by mosesyhc**
This is to provide a ROSE emulator wrapper in surmise

This might solve #41, providing an incremental enhancement

### CODE REVIEW

**Comment by wildsm** [comment]
@mosesyhc - is this still a draft PR or ready for review?

**Comment by mosesyhc** [comment]
Yes it is ready for review. @wildsm

**Review by wildsm — APPROVED** [review]
Looks great, thank you

**Comment by wildsm** [comment]
@mosesyhc Can you please take another quick look? I messed up something in the conflict resolution

**Comment by mosesyhc** [comment]
Keeping the develop-rose branch around until all merges happen for v0.2 release, in case anything is incorrect somehow..

**Pull request merged**
