### PR TITLE
Fix test

### PR DESCRIPTION
**Pull request by mosesyhc**

### CODE REVIEW

**Comment by mosesyhc** [comment]
Identified github action issues:
- since pip 23, editable pip encounters error of accessing site-packages (see https://github.com/pypa/pip/issues/11972#issuecomment-1511105078)
- installing `wheel` before pip install is a temporary fix

**Comment by mosesyhc** [comment]
- The setup configuration is migrated to setuptools with pyproject.toml.  
- Currently py37 is removed. numpy with py37 is causing an import error and needs further investigation. 
- macos tests are very slow.

**Comment by wildsm** [comment]
Looks great thank you so much.

One question:
What is pyproject.toml for and can it be directly referenced in setup.py?

One reason for the question is that M1 and R3 of https://github.com/surmising/surmise/blob/fix-test/surmisebandsdk.md
specifically reference that this info is in setup.py

**Comment by mosesyhc** [comment]
pyproject.toml is essentially a configuration file for setup, that [pip has moved towards since v23.2.1](https://pip.pypa.io/en/stable/reference/build-system/).

One other space from Python is PEP 518, with the following snippet:
> This PEP attempts to rectify the situation by specifying a way to list the minimal dependencies of the build system of a project in a declarative fashion in a specific file. This allows a project to list what build dependencies it has to go from e.g. source checkout to wheel, while not falling into the catch-22 trap that a setup.py has where tooling can’t infer what a project needs to build itself.  (https://peps.python.org/pep-0518/)

Regarding BAND SDK (https://github.com/surmising/surmise/blob/fix-test/surmisebandsdk.md):
- M1: `python setup.py install` still successfully build. Similarly, `pip install` also works.  
- R3: `surmise.egg-info/requires.txt` is still produced with either build call.  `surmise.egg-info` is identical.

**One possible solution**:
It does not hurt (though not good in my opinion) to repeat the requirements in `setup.py`.  That way we still comply to BAND SDK.  See [8fef364](https://github.com/surmising/surmise/pull/50/commits/8fef3646ed5608e9da1209a6fe128107b7affed1)

**Review by wildsm — APPROVED** [review]
Thanks @mosesyhc !

**Pull request merged**
