### PR TITLE
Update requirements.txt to handle sklearn install error

### PR DESCRIPTION
**Pull request by mosesyhc**
pip install sklearn is deprecated.

### CODE REVIEW

**Comment by mosesyhc** [comment]
Attempt to fix #44

**Comment by wildsm** [comment]
I need help with the tests. I also suggest having the matrix of tests be much smaller.

I would edit requirements.txt to have
numpy>=1.8.2
scipy>=1.10.0

the Readme would also need to be updated.

**Comment by mosesyhc** [comment]
What is an ideal test time? Should we separate out more time-intensive tests (for accuracy checks maybe) from the structure tests (to make sure nothing breaks)?

**Comment by wildsm** [comment]
At this point, I would keep the current tests as is but focus on a single numpy, scipy version

**Review by wildsm — APPROVED** [review]

**Comment by wildsm** [comment]
I'm going to go ahead and merge this PR and have opened #48

**Pull request merged**
